name: MAIN CI
on:
  push:
    branches:
      - "main"

jobs:
  update-backend:
    runs-on: [ self-hosted, main ]
    steps:
      - uses: actions/checkout@v3
        name: Build backend
        run: docker build -t lev-service:latest backend/
      - name: Up backend
        run: docker-compose -f docker-compose.yml up -d lev-service
      - name: Update nginx
        run: |
          sudo cp nginx.conf /etc/nginx/conf.d/lev.conf
          sudo nginx -s reload